drop table t_user if exists;

create table t_user(id bigint generated by default as IDENTITY,user_name varchar(40),phone varchar(11),age int(3),balance decimal(10,2), create_time DATE ,primary key(id) );